
#Define which mobs should spawn. (Default: "true" for all mobs.)
[Mob_Spawning]
	Hunter = true
	Jungle_Creeper = true
	Lost_Miner = true
	Desert_Bandit = true
	Frozen_Zombie = true
	Muddy_Pig = true
	Camel = true
	Duck = true
	Zebra = true
	Frog = true

	#Extensive Config options for all the Mobs.
	[Mob_Spawning.Mobs]

		#Config options for the Hunter and Variants.
		[Mob_Spawning.Mobs.Hunter]
			#Spawn weight for the Hunter. (Default: 90)
			#Range: 0 ~ 10000
			weight = 90
			#Minimum amount of Hunters to spawn in a group. (Default: 1)
			min_group = 1
			#Maximum amount of Hunters to spawn in a group. (Default: 3)
			max_group = 3
			#Drop chance for the "Hunter's Bow" (Default: 8)
			#Range: 0 ~ 200
			drop_chance = 8
			#Spawn Biomes/BiomeTags where the Hunter will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["minecraft:is_jungle"]

			#The Head Hunter is a special variant of the Hunter. It's even more deadly!
			[Mob_Spawning.Mobs.Hunter.Head_Hunter]
				#Enables the spawning of the Head Hunter. (Default: true)
				head_hunter = true
				#Spawn weight for the Head Hunter. (Default: 10)
				#Range: 0 ~ 10000
				weight = 10

				#This is the interval between shots.
				[Mob_Spawning.Mobs.Hunter.Head_Hunter.Firing_Speed]
					#Tweak the firing speed of the Head Hunter. (Default: 20)
					#For reference: The Vanilla Skeleton firing speed is: 40.
					firing_speed = 20
					#Tweak the firing speed of the Head Hunter for the Hard Difficulty. (Default: 10)
					#For reference: The Vanilla Skeleton firing speed for the Hard difficulty is: 20.
					firing_speed_hard = 10

		[Mob_Spawning.Mobs.Jungle_Creeper]
			#Spawn weight for the Jungle Creeper. (Default: 90)
			#Range: 0 ~ 10000
			weight = 90
			#Minimum amount of Jungle Creepers to spawn in a group. (Default: 1)
			min_group = 1
			#Maximum amount of Jungle Creepers to spawn in a group. (Default: 3)
			max_group = 3
			#Spawn Biomes/BiomeTags where the Jungle Creeper will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["minecraft:is_jungle"]

		[Mob_Spawning.Mobs.Lost_Miner]
			#Spawn weight for the Lost Miner. (Default: 160)
			#Range: 0 ~ 10000
			weight = 160
			#Minimum amount of Lost Miners to spawn in a group. (Default: 1)
			min_group = 1
			#Maximum amount of Lost Miners to spawn in a group. (Default: 3)
			max_group = 3
			#Drop chance for the "Miner's Pickaxe" and "Miner's Helmet" (Default: 8)
			#Range: 0 ~ 200
			drop_chance = 8
			#Spawn Biomes/BiomeTags where the Lost Miner will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["minecraft:is_overworld"]

		[Mob_Spawning.Mobs.Desert_Bandit]
			#Spawn weight for the Desert Bandits. (Default: 70)
			#Range: 0 ~ 10000
			weight = 70
			#Spawn Biomes/BiomeTags where the Desert Bandits will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["forge:is_desert"]

		[Mob_Spawning.Mobs.Frozen_Zombie]
			#Spawn weight for the Frozen Zombie. (Default: 95)
			#Range: 0 ~ 10000
			weight = 95
			#Minimum amount of Frozen Zombies to spawn in a group. (Default: 4)
			min_group = 4
			#Maximum amount of Frozen Zombies to spawn in a group. (Default: 4)
			max_group = 4
			#Spawn Biomes/BiomeTags where the Frozen Zombie will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["forge:is_snowy"]
			#Removes Vanilla Zombie Spawning in these Biomes. (Default: true)
			remove_vanilla_zombies = true

		[Mob_Spawning.Mobs.Muddy_Pig]
			#Spawn weight for the Muddy Pig. (Default: 10)
			#Range: 0 ~ 10000
			weight = 10
			#Minimum amount of Muddy Pigs to spawn in a group. (Default: 4)
			min_group = 4
			#Maximum amount of Muddy Pigs to spawn in a group. (Default: 4)
			max_group = 4
			#Spawn Biomes/BiomeTags where the Muddy Pig will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["forge:is_swamp"]
			#Removes Vanilla Pig Spawning in these Biomes. (Default: true)
			remove_vanilla_pigs = true

		[Mob_Spawning.Mobs.Camel]
			#Spawn weight for the Camel. (Default: 1)
			#Range: 0 ~ 10000
			weight = 1
			#Minimum amount of Camels to spawn in a group. (Default: 2)
			min_group = 2
			#Maximum amount of Camels to spawn in a group. (Default: 3)
			max_group = 3
			#Spawn Biomes/BiomeTags where the Camel will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["forge:is_desert"]

		[Mob_Spawning.Mobs.Duck]
			#Spawn weight for the Duck. (Default: 10)
			#Range: 0 ~ 10000
			weight = 10
			#Minimum amount of Ducks to spawn in a group. (Default: 4)
			min_group = 4
			#Maximum amount of Ducks to spawn in a group. (Default: 4)
			max_group = 4
			#Spawn Biomes/BiomeTags where the Duck will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["forge:is_swamp"]
			#Removes Vanilla Chicken Spawning in these Biomes. (Default: true)
			remove_vanilla_chickens = true

		[Mob_Spawning.Mobs.Zebra]
			#Spawn weight for the Zebra. (Default: 12)
			#Range: 0 ~ 10000
			weight = 12
			#Minimum amount of Zebras to spawn in a group. (Default: 2)
			min_group = 2
			#Maximum amount of Zebras to spawn in a group. (Default: 4)
			max_group = 4
			#Spawn Biomes/BiomeTags where the Zebra will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["minecraft:is_savanna", "minecraft:plains"]

		[Mob_Spawning.Mobs.Frog]
			#Spawn weight for the Frog. (Default: 10)
			#Range: 0 ~ 10000
			weight = 10
			#Minimum amount of Frogs to spawn in a group. (Default: 2)
			min_group = 2
			#Maximum amount of Frogs to spawn in a group. (Default: 4)
			max_group = 4
			#Spawn Biomes/BiomeTags where the Frog will spawn.
			#To add Biomes or BiomeTags:
			#["BiomeTag 1", "BiomeTag 2", "Biome 1", "Biome 2", etc...]
			#To check for multiple mandatory matching BiomeTags per Biome:
			#["BiomeTag 1 & BiomeTag 2 & etc..."]
			spawn_biomes = ["forge:is_swamp"]

#Disable Enchantments from Better Default Biomes. (Default: "true" for all Enchantments.)
[Enchanting]
	#Mobs in a small area around the Player get the Glowing effect.
	enable_scout = true
	#Bows/Crossbows do more damage against animals.
	enable_hunting = true
	#Horse Protection Enchantments like the Vanilla Protection Enchantments for the Player.
	enable_horse_protection = true
	#Thorns for Shields.
	enable_spikes = true
	#Knockback for Shields.
	enable_guard = true
	#Horses float in water.
	enable_floating = true

	[Enchanting.Smelting_Touch]
		#Smelt blocks when mining.
		enable_smelting_touch = true
		#Sets Mobs/Players on fire when attacked.
		set_on_fire = true

#Item configurations for Better Default Biomes. (Default: "true" for all settings.)
[Item]

	[Item.Torch_Arrow]
		#Set Mobs/Players on fire when hit by a Torch Arrow.
		set_on_fire = true

#Trading configurations for Better Default Biomes. (Default: "true" for all settings.)
[Trading]
	#Enable trades added by Better Default Biomes.
	enable_trades = true

#Debug options for Better Default Biomes.
[Debug]
	#Enables the "BetterDefaultBiomes (Extra Info)" files to be generated by the mod. (Default: false)
	extra_info_files = false

	#Logger options.
	[Debug.Loggers]
		#Prints a message to the log for each Biome that has been registered for generation. (Default: false)
		generation_logger = false
		#Enables a logger visualizing the registration of Mob spawns. (Default: false)
		spawn_logger = false
		#Enables a logger visualizing the registration of Mob spawns that spawn in all Overworld Biomes by default. This is separate to avoid spam. (Default: false)
		spawn_logger_all = false
		#Enables a logger for more info about the removed vanilla spawns. (Default: false)
		remove_spawn_logger = false

	#Define which mobs should have the Glowing effect. Useful for debugging Mob spawning. (Default: "false" for all mobs.)
	[Debug.Glowing_Mobs]
		Hunter = false
		Jungle_Creeper = false
		Lost_Miner = false
		Desert_Bandit = false
		Frozen_Zombie = false
		Muddy_Pig = false
		Camel = false
		Duck = false
		Zebra = false
		Frog = false

