modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Xratedjunior/Better-Default-Biomes/issues"

[[mods]] #mandatory
	modId="${mod_id}"
	version="${mod_version}-Alpha"
	displayName="${mod_name}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/better-default-biomes"
	logoFile="BetterDefaultBiomes.jpeg"
	authors="${mod_authors}"
	displayTest="MATCH_VERSION"

	description='''${mod_description}'''

[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"
